### ISSUE TITLE
WindowCovering Stop function and program button

### ISSUE THREAD

**Issue by PrimaryInc** [jvmahon/Homebridge-HomeSeer4#100]
Hi, 

This is not a issue per definition, but the ability to send stop command to awning or zip screens konfigured in HomeSeer would be great.
Stop button is present in HomeSeer, same is it with program button.
Is it possible to integrate this?

![HS buttons](https://user-images.githubusercontent.com/45151934/89404416-3fef7280-d71a-11ea-8ed5-18ca9aece2d3.PNG)

**Comment by jvmahon** [comment]
HomeKit follows a percentage ( 0 - 100%) model for shade control which is different from the  Up / Stop / Down model used by simple shades. As a way of making HomeKit work with typical Up / Stop / Down shades, I have homekit always show the shade at 50%, and by swiping to a higher level, it then triggers the up, by swiping down, it triggers down, and then returns to the 50% level. This operation isn't really compatible with a "stop" function so I don't have any easy way of integrating this

I would prefer if HomeKit provided some way of defining buttons for the shades as an option so that I could do a Up / Down / Stop type control, but it isn't available.
