### ISSUE TITLE
Solved - Multilevel 4 speed fan issues

### ISSUE THREAD

**Issue by tay1orjones** [jvmahon/Homebridge-HomeSeer4#128]
Hi! Thanks for your work on this plugin, it's so great to have control of z-wave devices in homekit 🎉 

My issue is with a Z-Wave HomeSeer HS-FC200+ Fan Controller that supports 4 fan speeds. Here's my status graphics for it:

![image](https://user-images.githubusercontent.com/3360588/102166901-d5320e80-3e52-11eb-96d8-03cf652bc515.png)

At first I added this as a simple `Fan`, but it was a binary switch and only did on/off. Through issues here I found out about `MultilevelFan` and have configured it as so:

```
"accessories": [
    {
        "type": "MultilevelFan",
        "ref": 189,
        "onValue": 99,
        "offValue": 0
    }
 ],
```

I now get a slider in the Home app, but the dim values aren't working. 0% turns the fan off and 100% turns the fan on, but nothing in between is working for me. I've tried `"onValue": 100,` as well as `"onValue": 255,`, but didn't see an improvement.

**Comment by wwhite74** [comment]
Have you tried setting the value by specifically asking siri to "set the fan to 24"
sometimes manually moving sliders doesn't always hit the magic number, and trying to set a value outside of those 5 numbers in your image won't do anything

you might need to do some scripting/events in homeseer, if you ask siri to set the fan to low/medium/full she'll set it to 25/50/100. and with your current device, those 3 values don't do anything.  "If Fan set to value between 1 and 25, set fan to 24." Not sure about this part, but you might also have to add dummy values to fill in the gaps, so homeseer doesn't refuse the command outright. (new range value 1-23 and give it a name)

**Comment by jvmahon** [comment]
I'd have to go back and look at the code again, but I believe if "Control Use" is set to "Dim" it will automatically configure as a multiLevel fan. In any case, the MultilevelFan override that you used is more certain.
HomeSeer is a bit inconsistent in how it sets up the Control use field.

In any case, as to the "bigger" problem, the issue is the way that HomeSeer set up Status Graphics. Since they didn't include the 1-23, 25-48, 50-73, 76-78 values, those values won't get passed on to the switch and are ignored.

The solution is to change these to ranges. So, delete the current values for status 1, 2, 3, and 4, and re-create them as ranges

There's an example in the Wiki for the FC-200 when set in 3-speed mode, but it should be pretty easy to adapt to 4-speed mode that you are using. Read the notes on that page carefully - I think there are some minor errors in the configuration shown in the pasted image, but they can easily be fixed. See https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Fan-Controller-Support

**Comment by jvmahon** [comment]
I haven't heard back further, so I'm closing this out.

**Comment by tay1orjones** [comment]
Thanks for the help! I finally got around to resolving this, the following is what worked:
<img width="979" alt="image" src="https://user-images.githubusercontent.com/3360588/178120583-a82e10cf-15d8-4fba-a6a2-7c71536b23cc.png">
