### ISSUE TITLE
Zigbee light through HS3

### ISSUE THREAD

**Issue by villamann** [jvmahon/Homebridge-HomeSeer4#137]
I have Zigbee lights from both deCONZ and Hue bridge exposed to HS3 through the JowiHue plug-in. In one of my setups these bulbs are again exposed to Homebridge from HS3. Whenever HS3 or Hue app sets one of the Zigbee bulbs to a value above 99 (0-254), they are immediately set down to 99. When I take the bulbs out of the config they operate as expected.
My intermediate solution was to change the device type to switch, then they accept 254 as On-value.

**Comment by jvmahon** [comment]
Are you using the "simple" light setup procedure describe here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Setting-Up-Your-Config.json-file where you set up the lights as an array of reference numbers like this:
`````
"Lightbulbs": 	[200, 210],
`````
This was mostly tested with Z-wave devices which function on 0 - 99 values and don't recognize 100. It seems like a very bizarre and odd choice in the z-wave standards, but its what they do. A lot of these "simple" configurations were developed / tested around Z-wave.

Try using one of the more "complete" or advanced setup configuraitons. That is, for your bulb, add a detailed setup using the "levels" characteristic as described in Section G, above.  So, for example, in the "accessories" section of your config.json you would enter:
`````
					{
						"type": "DimmingLight",
						"name": "Whatever your name is",
						"ref":  ##,
						"onValue": 100,
						"levels":100,
						"offValue": 0
					},
`````

You may not need the onValue / offValue as that may still be automatically detected (not sure with Zigbee), so it could be as simple as:

`````
					{
						"type": "DimmingLight",
						"name": "Whatever your name is",
						"ref":  ##,
						"levels":100
					},
`````

Be sure to remove the reference from the "Lighbulbs" simple configuration array since you don't want to add it twice and it will likely cause an error.

For further reference on all configuration parameters, see: https://github.com/jvmahon/Homebridge-HomeSeer4/blob/master/config/config.complex.json

**Comment by villamann** [comment]
Thanks for pointing me in the right direction, the Levels parameter solved the problem. Levels 100 gave the same result, but setting Levels to 254 gave the lightbulb the same range as lights in HS3.
