### ISSUE TITLE
This plugin generated a warning from the characteristic 'Target Temperature'

### ISSUE THREAD

**Issue by villamann** [jvmahon/Homebridge-HomeSeer4#140]
OS - Win10
Node - 14.16.0
Plugin - homebridge-homeseer4 v1.0.16

I`m using the thermostat device in our cabin, and it keeps the inside temperature at 8 degrees celsius. I now get the following warning for each thermostat every five minutes:

_This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 8 exceeded minimum of 10_

Any chance to set the minimum number lower in the plugin?

**Comment by jvmahon** [comment]
Please update plugin to 1.0.17.

I've added range checking so that the plugin won't try to set the temperature to a invalid value. This isn't quite what you asked for, but it will eliminate the error. If you set your cabin thermostat below 10, iOS Home will now show it at the lowest value - i.e., 10, rather than generate an error. 

I'm not using HomeSeer anymore, and the change you asked would require more extensive testing (the thermostat code is very tricky), so I don't want to do that right now.

Please confirm the plugin is working / doesn't crash after these changes.

**Comment by villamann** [comment]
Thanks, works and no more warnings.
