### ISSUE TITLE
Would you be open to code refactors (in a series of PRs)?

### ISSUE THREAD

**Issue by igrayson** [jvmahon/Homebridge-HomeSeer4#150]
Hi, I just moved from vera to homeseer for my home control, so your homebridge plugin is a huge value for me (I use homekit extensively).

At five years, the plugin's codebase is a little old for Javascript, which has progressed a lot in that span.

Would you be open to refactors to incorporate some more recent javascript standards? Some options I'm considering:
- [ ] codestyle/linting (automated).
- [ ] convert to typescript
- [ ] build/release scripting

Just checking your appetite for improvements like these!

**Comment by jvmahon** [comment]
Hi,
Thanks for checking.

As you've noticed, I rarely  touch this code anymore. There are a few reasons for that: 1) I no longer use HomeSeer so I don't have the ability to do thorough testing of changes (I still have the software so I can do small test, but all my devices are now on Hubitat); and 2)  People have not reported any significant defects / lack of functionality; and 3) my "real work" takes up most of my time so I don't have time for anything significant. These points make me reluctant to do anything with the code (I'll still address the minor request, but I'm not touching "big" stuff).

This being said, if you wanted to make some of these improvements you're suggesting, and submit by a PR, I'd still consider it -- but I caution that, due to personal time limits, it will take a long time for me to review / integrate any "big" changes.  I wish I could be more helpful -- I like the idea of adding typescript, etc. and would do that if the code was still "evolving" -- but I also want to be realistic and not have you frustrated that you did a lot of work to submit changes that take me forever to review.
