### ISSUE TITLE
Firewall issue Windows defender, home edition

### ISSUE THREAD

**Issue by TFL999** [jvmahon/Homebridge-HomeSeer4#189]
Hello,

In the past I had homebridge installen on the same PC as homeseer is running.
I did a complere clean install of HS4 on a windows home edition laptop, but apparantly it is not possible anymore to install homebridge on Windows home edition. 
So I installed it on a raspberry pi 3. Homebridge as well the Homebridge-HS4 plugin seemed to work fine, but it couldn't connect to the ascii port 11000 which was set to enable. When I de-activate the windows defender firewall, it connects to homeseer.
Homeseer is excluded in the firewall list. 
Can anybody help me how to setup the windows defender firewall in a way that I can enable windows defender and still Homebridge can connect on port 11000?

best regards,
TFL

**Comment by jvmahon** [comment]
Did you fix this issue? Unfortunately, I don't have any advice to give on this.

**Comment by jvmahon** [comment]
Also, if you have HomeSeer on a Raspberry PI, why not also install Homebridge on the same Raspberry PI?

The Raspberry PI has plenty of processing power to run both and HomeBridge will actually work faster if you don't have to communicate between two computers (communicating across Ethernet or WiFi is a relatively "expensive" operation and my experience is that dividing the apps between two computers causes more delay than any processing burden from having both apps on the same RPi). Admittedly, this is a "it feels faster when both are on the same computer" type conclusion, rather than any rigorous testing.

**Comment by TFL999** [comment]
thankz for the reply
I couldn't find the solution yet. For now the windows defender firewall is turned off to get it to work.

Homeseer is not installed on a raspberry PI but on a windows laptop. Because of some plugins that are running.  And because it is windows home edition, I can't install hombridge on that laptop.  That is why it is on two different systems. 

I will make a post on the homeseer forum as well, maybe somebody out there knows the solution.
