### ISSUE TITLE
Events double triggering

### ISSUE THREAD

**Issue by darrenmcuk** [jvmahon/Homebridge-HomeSeer4#196]
So here is my config snippit..

            "events": [
                {
                    "name": "Hallway OccuMotion",
                    "eventGroup": "Lights",
                    "eventName": "Hallway Motion"
                }

Now this exposes a homekit switch...with no issues....however when it is switched on...it seems to triggered the even twice..
1/02/2023 09:56:50
HomeSeer
Device Control
Device: Ground Floor Hallway Hallway Occupied Control to On (100)

1/02/2023 09:56:50
HomeSeer
Event
Event Trigger "Lights Hallway Motion"

1/02/2023 09:56:48
HomeSeer
Device Control
Device: Ground Floor Hallway Hallway Occupied Control to On (100)

1/02/2023 09:56:48
HomeSeer
Event
Event Trigger "Lights Hallway Motion"

What am I doing wrong?

Thanks,
Darren

**Comment by jvmahon** [comment]
I'm not sure what is wrong here.

My recommendation is to try running events using the virtual switch method that I describe here:  https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Running-HomeSeer-Events

I no longer use HomeSeer though I try to do updates to the plugin code from time-to-time. This "event" feature is really more of a legacy holdover that I've considered removing since the virtual switch method seems to be more reliable.
