### ISSUE TITLE
Homebridge -unable to connect to ASCII port

### ISSUE THREAD

**Issue by roeshop** [jvmahon/Homebridge-HomeSeer4#200]
I've been running Homebridge w/ Homeseer for quite a while.  But know I have an issue.

Homebridge will start up fine - and connects to Homeseer.  But then I get an error 'unable to to connect to ASCII port.

I have made some changes recently - I switched to Eero.
I had my Homebridge running on RPI.

Other people seemed to have many issues with the Eero and Homebridge on RPI, so I switched and set up Homebridge on my Windows 10 (creating VM), Homeseer is also on this same machine.

But It still get the same error.  Please help

![error](https://github.com/jvmahon/Homebridge-HomeSeer4/assets/20630544/afbef125-c04e-4438-b941-3c912a565237)
![Homeseer](https://github.com/jvmahon/Homebridge-HomeSeer4/assets/20630544/7163388f-7a30-48a9-836e-015cab4438ee)

**Comment by teladog01** [comment]
Is Homebridge running in Docker? If so, did you map port 11000? Also I would look at the VM networking.

But your most pressing issue should be changing your MyHS password ASAP 😬

**Comment by roeshop** [comment]
Thanks for the reply…. Yes, sorry screwed up on the password.  Thanks for the head up. 

You asked if my homebridge is running Docker.  I have no idea.  To sound like an idiot…what is Docker?

**Comment by teladog01** [comment]
Well if you were using Docker I think you would probably know it. [Specifics of Docker](https://en.wikipedia.org/wiki/Docker_(software)) are [well documented](https://docs.docker.com) so I won't get into that.

Your issue is most likely just a networking issue, and not an issue with Homebridge-HomeSeer4 per se. Traffic from Homebridge-HomeSeer4 on port 11000 isn't getting to where it needs to go (HomeSeer).

You said:

>so I switched and set up Homebridge on my Windows 10 (creating VM)

So you need to look at the networking of the VM environment you setup...

What hypervisor is running the VM?

What OS is the VM running?

How did you install Homebridge in the VM (Docker or package install would be a couple options here)?

Is Homebridge on the same subnet as HomeSeer (192.168.1.x)?

I'll do my best to help, but I mostly just wanted to let you know you had given potentially the whole world access to your house 😉

**Comment by roeshop** [comment]
Understand, any kind of help would be greatly appreciated.
I agree it is probably some type of networking issue.
It is strange, I can’t control any of the devices, but they will update their status after a 10-20 minute delay.  So it is connecting, but just not keeping it.

My VM setup
- I’m running VM on a Windows 10 Pro machine
- The hyper visor is running on the windows Hyper-V Manager 
- it is running on a different subset
- 
Sorry I have very limited experience with VM.  Is there a way to run it on the same subset? Or is there something else I can look at to fix the networking issue.

**Comment by roeshop** [comment]
Here is a screen shot of the VM...it looks like it might be using Docker. 
Not sure it there is an easy way to make it use the same subset
![Screenshot vm](https://github.com/jvmahon/Homebridge-HomeSeer4/assets/20630544/95f76884-2a26-4465-937e-e487bb27dc43)

**Comment by jvmahon** [comment]
> It is strange, I can’t control any of the devices, but they will update their status after a 10-20 minute delay. So it is connecting, but just not keeping it.

No, the ASCII port is not connecting. What you are seeing is something different. Every 20 minutes or so (I don't remember the specific timing), the plugin pulls all the data from HomeSeer using HTTP in a single bulk transfer - this was included as a "safety" to make sure no changes were missed on the ASCII port. So this update every 20 minutes just means that HTTP access is working.  However, ASCII access is still needed for real-time updates.

After enabling ASCII port access in HomeSeer, but sure to restart HomeSeer.  HomeSeer doesn't actually effect the change in ASCII port access unless you restart it (the HomeSeer UI gives not indication that you have to reboot, but you do).

**Comment by roeshop** [comment]
sorry to be a pain - but I've had no luck.

I've confirmed that 'Enabling ASCII port' was checked, and the port #'s match.  I've restarted Homeseer, Homebridge and my computer many times.  

I'm assuming the issue is with Eero - that's the change point for when it stopped working.
Is there a setting I need to change within Eero?

Also you asked if my VM Homebridge was on the same subnet.  It is not.  
Is there a way to get it on the same subnet?

**Comment by jvmahon** [comment]
I'm not sure how to help you.  Last guess - If HomeSeer / Homebridge are on the same VM, maybe try configuring Homebridge with an address of 127.0.0.1 for HomeSeer.

**Comment by teladog01** [comment]
>I'm assuming the issue is with Eero - that's the change point for when it stopped working.

My understanding from your initial post is that you also changed Homebridge from running on a RPi to a Windows VM. This could just as well be the cause of your networking issue as the Eero. Also, you still haven't determined if Docker is in the mix. Because if it is and you don't have the ASCII port properly mapped in the Docker container, then it will never work.

Did the Homebridge switch (RPi to Windows VM) happen at the same time as the Eero install? Or was this something that happened later? If later, did the ASCII port ever connect when the Eero was installed, when Homebridge was still on the RPi (before you moved it to the Windows VM)?

You've also stated twice now that Homebridge and HomeSeer are not on the same subnet, yet your screenshots show that Homebridge is at 192.168.1.88 and HomeSeer is at 192.168.1.112, which indeed ARE on the same subnet...🤷‍♂️
