### ISSUE TITLE
[homebridge-homeseer4] This plugin is taking long time to load and preventing Homebridge from starting

### ISSUE THREAD

**Issue by thetaz001** [jvmahon/Homebridge-HomeSeer4#205]
it appears my HS4 plug in, is not starting properly
might you please take a look and see if its me, or a bigger issue
thanks so much for supporting this!!

**Comment by jvmahon** [comment]
There's been no change to the plugin in quite a while, and no other complaints, so I think its your setup. 

I understand there's an updated Homebridge 2.0 out (maybe just in beta). I have not tested on that (and I don't plan to since I'm not using this plugin anymore). So if you're using that homebridge beta, you may want to go back to pre-2.0 Homebridge.

**Comment by thetaz001** [comment]
Hey there, thanks for that! you were correct i didnt realize my homeseer server had a web port issue, after a BAD reboot..
I rebooted it, and all is working fine again!
I'm sad to hear you wont be developing this any longer...
i REALLY rely on this...
and am heavily invested in homeseer, and love the homekit connection..
thanks for the help!!

**Comment by jvmahon** [comment]
Basically, I stopped developing both (1) because I haven't really needed to add anything in years, so there really isn't more for me to do, and (2) I'm now fully-in on using HomeAssistant which has built-in support for iOS home.
