### ISSUE TITLE
Naming update

### ISSUE THREAD

**Issue by mbaastrup** [jvmahon/Homebridge-HomeSeer4#34]
While testing the new HS4 bridge I have tried to figure out if there is a way - by deleting some cashing files or something like that - that will reinforce the device naming in iOS based on the config.json without taking away the identifier. 
Use case: A device is associated to a room in iOS. Renaming from HS3 or directly in config.json on the device, updating/chaining the name but without loosing the room association and/or automation rules in iOS.

**Comment by jvmahon** [comment]
I think the simple answer is "No."  Persistence of a device name is a "homebridge" function so there isn't much I can do about it in the plugin. But just in case I don't understand your question, here's a more technical description of how it works:

1. In homebridge, every HomeKit item is tracked by a variable "uuid_base" which must be unique. Usually you don't have to specify this - my plugin automatically generates a "uuid_base" that is unique for each HomeSeer device. (There are a few situations where you might want to specify the uuid_base such as is described here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Show-the-same-device-in-multiple-rooms )

2. The first time you add a device to your config.json file, Homebridge creates an entry in its database for that device and stores the device uuid_base information along with the device's name and other information. The name that gets stored is either:  (i) the name you set for the device in config.json; or (ii) if you didn't give the device a name, the plugin generates one by combining the HomeSeer Room Name with the HomeSeer Device name.

3. Once the uuid_base and name have been entered into the homebridge database in steps 1-2, the "name" value in your config.json is never used again. So, even if you change the name in config.json, that will have no effect. The only way to "reset" to the name in config.json is to either manually assign the device a unique "uuid_base" or else to delete homebridge's entire persistence database. This would "wipe out" any Automations you have set up on your iOS device and you would have to re-pair your phone with HomeBridge. I don't recommend trying this!

4. If you want to change the name after the first time that steps #1 and #2 have completed, you must do it by your iPhone / iPad. That is the only way to change the name without resetting the entire homebridge database.

There are some instructions for resetting the homebridge database in the wiki. Though not exactly on point, the general instructions are here: https://github.com/jvmahon/Homebridge-HomeSeer4/wiki/Devices-Not-Appearing-or-Updating-After-A-Change-to-Homebridge-or-config.json

**Comment by rrman** [comment]
When I need to rename a device, as jvmahon mentioned, only the name needs to be changed in the iOS Home app and not in config.json. However,  for my workflow, I like explicitly specifying the "name" parameter in config.json. To be consistent (in case I need to recreate my HomeKit database in the future), I also change the "name" parameter in config.json even though it won't be used unless the database is recreated.

Aside (a bit off topic): I like explicitly specifying the "name" parameter in my config.json since (a) it serves as a comment so I can easily tell what the entry in config.json is for (given that JSON doesn't allow comments and I have close to 200 devices) and (b) I use the  naming convention of "<room name> <device name>". When "<room name> <device name>" is used for the name, I can easily tell what the device is for in  the iOS home app and I easily assign it to the proper room. The iOS Home App is smart enough so that if you assign a device whose name is "<room name> <device name>" to the room "<room name>", then when you look at the iOS Home app GUI page for that room, the device shows up with the name "<device name>", as desired (i.e. the iOS Home App doesn't show "<room name> <device name>" in the device's name, since <room name> would be redundant and just take up more space. This is true for Apple's iOS Home App, at least.  I don't know about now, but a long time ago, the default name used by the homebridge plugin, if the "name" parameter isn't explicitly specified, was "<room name>.<device name>" (with a dot between the <room name> and <device name>)". I found that using a space instead of a dot worked better for me so that iOS only showed <device name> when the device is assigned to <room name>.

**Comment by jvmahon** [comment]
@rrman - FYI, the "." dot notation that used to separate the room name from the device name was changed and is now a space. I changed that a few builds ago, but I think that was after you had set up your system.

**Comment by jvmahon** [comment]
I've updated the Wiki to incorporate additional information on device naming so I'm closing this comment. Re-open if you think an issue remains.
