### ISSUE TITLE
iOS scenes

### ISSUE THREAD

**Issue by dibble9012** [jvmahon/Homebridge-HomeSeer4#44]
After changing to the homeseer4 plugin (vs the 2018) it seems like iOS scenes don’t work correctly. Some of the lights turn off but others don’t. They show as off in the home app but don’t actually turn off. In order to manually turn them off I have to open the home app and turn them on and then back off.

**Comment by jvmahon** [comment]
I'll check for that, but I haven't seen the issue myself.  

First, try updating to the latest (last night's) iOS release 13.3.1.  Does this fix the issue?

Have you tried re-starting HomeSeer / HomeBridge and, if so, does that affect whether the error occurs?

Are you on the latest HomeSeer 3 / Z-Wave plugin release (5.0.0.548 for HomeSeer; 3.0.2.0 for Z-Wave Plugin).

Else,I need to try and re-create the issue and to understand it some more, so can you provide some more details:
How many lights are in the scene? I.e., does this only affect scenes with large #s of lights?

Try your scene while looking at the Homebridge output - does it show that all the commands are being sent to HomeSeer?

What types of lights (z-Wave, hue, dimmers, binary, etc)?

Is the behavior predictable - i.e., does this occur every time?

Do you have HomeBridge and HomeSeer on the same computer or are they run from different computers?

**Comment by jvmahon** [comment]
I did some testing, and I think there is an iOS bug in scenes. Did you recently upgrade iOS (i.e., since using the -2018 plugin)?

Fortunately, I think there's a fix which is to delete and re-create the problem scenes.

Here's what I did to create the error:

- I set up an "Off" scene each with 18 devices, From HomeSeer, I manually turned on each light. I then turned the "Off" using the scene. All the devices turned Off.
- I then added an "On" scene with the same devices. Turned them all "On" - All as expected
- Then I turned them all "Off" - again, as expected, all lights turned off. But then the "scene" buttons in iOS became stuck - both the "On" and "Off" scenes were showing as activated and they could no longer be used. 
-Both scenes showed as activated even though iOS showed each individual device as being set to "Off".  It shouldn't have been possible for both "On" and "Off" to show as activated as they are mutually exclusive.
- I then had to delete the two scenes to get them "un-stuck." After I re-created the scenes, all worked as expected.
- Although the exact pattern of your issue is different, the issue I encountered suggest there is something in iOS that is messing up. So, please try the "delete" then "re-create" route to try and fix the issue.

**Comment by dibble9012** [comment]
Installed latest update, no change. 

Restarting both homebridge and HomeSeer have no effect.

Latest version of HomeSeer and z-wave plugin. 

I’ll check to make sure all the commands are being sent to HomeSeer tonight.

All are z wave lights with a mixture of dimmers and binary switches.

It happens every time I run the event. I’ll try deleting the event and setting it up again and report back.

**Comment by jvmahon** [comment]
Thanks. If I could re-create the issue, it would help. Unfortunately, I can't seem to re-create it  as my scenes are working in the revise plugin (other than the issue described above which required that I delete /  re-create a scene).  By the way, I'm also using the latest version of node (13.7).  One other thought - I found that npm doesn't always properly update homebridge and the plugins and found that I recently had to fully delete and re-install homebridge and all plugins to get npm to do a proper installation of the hap-nodejs layer that is used by the code. Consider that as a next step if deleting / re-creating the scene doesn't work.

Also, looking at the homebridge console, does it report that commands are being sent to Homeseer? If commands are being sent, and HomeSeer isn't processing them, it may be a Z-Wave issue. On occasion, I've had to reset my z-Wave interface using the "Restart THIS Interface" command for your Z-Wave controller (I don't think this issue has anything to do with Homebridge). 

![image](https://user-images.githubusercontent.com/15061942/73402390-2e389880-42bb-11ea-8bf1-552d00437af0.png)

**Comment by jvmahon** [comment]
If you have to re-build the scene, can you try it a few devices at a time.
That is, create the new scene with just a couple of devices out of your desired set. If it works, add a few more, if it breaks - observe when and which devices., then remove the devices that broke the scene and add the remainder. Basically, the goal is to determine if there is a particular subset of devices that is causing the problem and then focus on what might be special about them.

**Comment by dibble9012** [comment]
Ok after a bit of testing, I get this error showing up with as few as 3 devices added to a scene.

<img width="1259" alt="Screen Shot 2020-01-29 at 3 59 08 PM" src="https://user-images.githubusercontent.com/6963660/73408544-6aff9200-42b1-11ea-8335-70807055ff41.png">

**Comment by jvmahon** [comment]
That was helpful. I was able to re-create the error, so I hope to be able to track it down.

**Comment by jvmahon** [comment]
Try 0.0.41 and please let me know if it works.

For some bizarre reason, and I have no idea why, if I display the command string being sent to HomeSeer before sending it, then I don't get the error; but if I don't display the command string, I get an error. So that's the fix - i.e., to display the command string before sending it. There is no way this should work, but it seems it does - this must be an error in string handling in nodejs.

**Comment by Sinandgrin** [comment]
> It seems the problem still arises if the scene has many devices. Based on this, I think the issue is that HomeSeer may not like it if too many commands are sent in a short period of time. Forcing the plugin to print the command probably added a tiny bit of delay which helped prevent the error for a scene with a small number of devices, but the problem still arises if many commands are sent. So, with that in mind, I think I just need to figure out a way of adding a bit of delay between commands if many are being sent. I suspect the solution will be to go back to using the HTTP interface. This seems like a weekend project!

I'm watching this closely as I am experiencing this same issue. I have Homekit scenes that send device updates to many Homeseer devices and I am getting some devices to respond and update and others that are not. I have a work around where I created a slew of Homeseer events that carry out each of the desired sets of device updates and then I trigger those events from Homekit, but this is not ideal and I'd much rather be able to natively define the scene in homekit.

**Comment by jvmahon** [comment]
Try 0.0.42.
I reverted to the HTTP interface that I used to use. It seems this is a case where the slowness of the http protocol is advantageous in that it doesn't overload HomeSeer. Give a try and see if it now works O.K. for you.

**Comment by dibble9012** [comment]
That update seems to have fixed it.

**Comment by jvmahon** [comment]
Great. I also figured out how to fix it with the telnet interface using a sending queue to control the pacing. I may try that again after some more testing -- in which case, I may ask you to give it a try before I do a general deploy.

**Comment by Sinandgrin** [comment]
> Try 0.0.42.
> I reverted to the HTTP interface that I used to use. It seems this is a case where the slowness of the http protocol is advantageous in that it doesn't overload HomeSeer. Give a try and see if it now works O.K. for you.

Looks like the part of my issue where some lights were missed completely either being turned full On (100%) or full Off (0%) is now fixed but something is still not working correctly. I believe this is a slightly different issues so I will open a new issue since this one was closed.
