### ISSUE TITLE
Showing Watt and Voltage

### ISSUE THREAD

**Issue by jonnyhk** [jvmahon/Homebridge-HomeSeer4#60]
I can see the value in the log file but on the Accessories it say Light Sensor , Not Supported !
Any idea how to ?

![image](https://user-images.githubusercontent.com/62875291/79472853-a2eeb980-8004-11ea-9ea4-4aeda3fc1363.png)

**Comment by jonnyhk** [comment]
Some more info:
It's working on my phone :)
Only showing Not supported on my Homebridge ...

**Comment by jvmahon** [comment]
From what you are saying, my plugin is working for you.

It looks like your issue is with the homebridge-config-ui-x plugin. You'll have to go to that plugin's author to diagnose that one; however, according to this post, that plugin doesn't support the Light Sensor accessory:  https://github.com/oznu/homebridge-config-ui-x/issues/47

**Comment by jvmahon** [comment]
Since this seems to be an issue with a different plugin, I'm closing the comment.
